#include <stdio.h>
#include <stdlib.h>
#include <windows.h>

COORD coord = {0, 0};

void gotoxy(int x, int y)
{
    coord.X = x;
    coord.Y = y;
    SetConsoleCursorPosition(GetStdHandle(STD_OUTPUT_HANDLE), coord);
}

main()
{
    int Rsecond = 0, Lsecond = 0, Rhour = 0, Lhour = 0;
    while (!(Lhour == 9 && Rhour == 9 && Lsecond == 5 && Rsecond == 9)) {
        if (Rsecond % 2 == 0)
            Flasher1();
        else
            Flasher0();

        Digit(Lhour, 2, 1);
        Digit(Rhour, 22, 1);
        Digit(Lsecond, 46, 1);
        Digit(Rsecond, 66, 1);
        Rsecond++;
        if (Rsecond == 10) {
            Lsecond++;
            Rsecond = 0;
        }
        if (Lsecond == 6) {
            Rhour++;
            Lsecond = 0;
        }
        if (Rhour == 10) {
            Lhour++;
            Rhour = 0;
        }
        Sleep(999);
    }
    printf("\a");
}

Flasher0()
{
    gotoxy(39, 8);
    printf("  ");
    gotoxy(39, 9);
    printf("  ");
    gotoxy(39, 15);
    printf("  ");
    gotoxy(39, 16);
    printf("  ");
}

Flasher1()
{
    gotoxy(39, 8);
    printf("##");
    gotoxy(39, 9);
    printf("##");
    gotoxy(39, 15);
    printf("##");
    gotoxy(39, 16);
    printf("##");
}

Digit(int number, int x, int y)
{
    switch (number) {
    case 0 :
        Digit0(x, y);
        break;
    case 1 :
        Digit1(x, y);
        break;
    case 2 :
        Digit2(x, y);
        break;
    case 3 :
        Digit3(x, y);
        break;
    case 4 :
        Digit4(x, y);
        break;
    case 5 :
        Digit5(x, y);
        break;
    case 6 :
        Digit6(x, y);
        break;
    case 7 :
        Digit7(x, y);
        break;
    case 8 :
        Digit8(x, y);
        break;
    case 9 :
        Digit9(x, y);
        break;
    }
}

Digit0(int x, int  y)
{
    gotoxy(x + 1, y);
    printf("##########");
    gotoxy(x, y + 1);
    printf("#");
    gotoxy(x, y + 2);
    printf("#");
    gotoxy(x, y + 3);
    printf("#");
    gotoxy(x, y + 4);
    printf("#");
    gotoxy(x, y + 5);
    printf("#");
    gotoxy(x, y + 6);
    printf("#");
    gotoxy(x, y + 7);
    printf("#");
    gotoxy(x, y + 8);
    printf("#");
    gotoxy(x, y + 9);
    printf("#");
    gotoxy(x, y + 10);
    printf("#");
    gotoxy(x + 11, y + 1);
    printf("#");
    gotoxy(x + 11, y + 2);
    printf("#");
    gotoxy(x + 11, y + 3);
    printf("#");
    gotoxy(x + 11, y + 4);
    printf("#");
    gotoxy(x + 11, y + 5);
    printf("#");
    gotoxy(x + 11, y + 6);
    printf("#");
    gotoxy(x + 11, y + 7);
    printf("#");
    gotoxy(x + 11, y + 8);
    printf("#");
    gotoxy(x + 11, y + 9);
    printf("#");
    gotoxy(x + 11, y + 10);
    printf("#");
    gotoxy(x + 1, y + 11);
    printf("          ");
    gotoxy(x, y + 12);
    printf("#");
    gotoxy(x, y + 13);
    printf("#");
    gotoxy(x, y + 14);
    printf("#");
    gotoxy(x, y + 15);
    printf("#");
    gotoxy(x, y + 16);
    printf("#");
    gotoxy(x, y + 17);
    printf("#");
    gotoxy(x, y + 18);
    printf("#");
    gotoxy(x, y + 19);
    printf("#");
    gotoxy(x, y + 20);
    printf("#");
    gotoxy(x, y + 21);
    printf("#");
    gotoxy(x + 11, y + 12);
    printf("#");
    gotoxy(x + 11, y + 13);
    printf("#");
    gotoxy(x + 11, y + 14);
    printf("#");
    gotoxy(x + 11, y + 15);
    printf("#");
    gotoxy(x + 11, y + 16);
    printf("#");
    gotoxy(x + 11, y + 17);
    printf("#");
    gotoxy(x + 11, y + 18);
    printf("#");
    gotoxy(x + 11, y + 19);
    printf("#");
    gotoxy(x + 11, y + 20);
    printf("#");
    gotoxy(x + 11, y + 21);
    printf("#");
    gotoxy(x + 1, y + 22);
    printf("##########");
}

Digit1(int x, int  y)
{
    gotoxy(x + 1, y);
    printf("          ");
    gotoxy(x, y + 1);
    printf(" ");
    gotoxy(x, y + 2);
    printf(" ");
    gotoxy(x, y + 3);
    printf(" ");
    gotoxy(x, y + 4);
    printf(" ");
    gotoxy(x, y + 5);
    printf(" ");
    gotoxy(x, y + 6);
    printf(" ");
    gotoxy(x, y + 7);
    printf(" ");
    gotoxy(x, y + 8);
    printf(" ");
    gotoxy(x, y + 9);
    printf(" ");
    gotoxy(x, y + 10);
    printf(" ");
    gotoxy(x + 11, y + 1);
    printf("#");
    gotoxy(x + 11, y + 2);
    printf("#");
    gotoxy(x + 11, y + 3);
    printf("#");
    gotoxy(x + 11, y + 4);
    printf("#");
    gotoxy(x + 11, y + 5);
    printf("#");
    gotoxy(x + 11, y + 6);
    printf("#");
    gotoxy(x + 11, y + 7);
    printf("#");
    gotoxy(x + 11, y + 8);
    printf("#");
    gotoxy(x + 11, y + 9);
    printf("#");
    gotoxy(x + 11, y + 10);
    printf("#");
    gotoxy(x + 1, y + 11);
    printf("          ");
    gotoxy(x, y + 12);
    printf(" ");
    gotoxy(x, y + 13);
    printf(" ");
    gotoxy(x, y + 14);
    printf(" ");
    gotoxy(x, y + 15);
    printf(" ");
    gotoxy(x, y + 16);
    printf(" ");
    gotoxy(x, y + 17);
    printf(" ");
    gotoxy(x, y + 18);
    printf(" ");
    gotoxy(x, y + 19);
    printf(" ");
    gotoxy(x, y + 20);
    printf(" ");
    gotoxy(x, y + 21);
    printf(" ");
    gotoxy(x + 11, y + 12);
    printf("#");
    gotoxy(x + 11, y + 13);
    printf("#");
    gotoxy(x + 11, y + 14);
    printf("#");
    gotoxy(x + 11, y + 15);
    printf("#");
    gotoxy(x + 11, y + 16);
    printf("#");
    gotoxy(x + 11, y + 17);
    printf("#");
    gotoxy(x + 11, y + 18);
    printf("#");
    gotoxy(x + 11, y + 19);
    printf("#");
    gotoxy(x + 11, y + 20);
    printf("#");
    gotoxy(x + 11, y + 21);
    printf("#");
    gotoxy(x + 1, y + 22);
    printf("          ");
}

Digit2(int x, int  y)
{
    gotoxy(x + 1, y);
    printf("##########");
    gotoxy(x, y + 1);
    printf(" ");
    gotoxy(x, y + 2);
    printf(" ");
    gotoxy(x, y + 3);
    printf(" ");
    gotoxy(x, y + 4);
    printf(" ");
    gotoxy(x, y + 5);
    printf(" ");
    gotoxy(x, y + 6);
    printf(" ");
    gotoxy(x, y + 7);
    printf(" ");
    gotoxy(x, y + 8);
    printf(" ");
    gotoxy(x, y + 9);
    printf(" ");
    gotoxy(x, y + 10);
    printf(" ");
    gotoxy(x + 11, y + 1);
    printf("#");
    gotoxy(x + 11, y + 2);
    printf("#");
    gotoxy(x + 11, y + 3);
    printf("#");
    gotoxy(x + 11, y + 4);
    printf("#");
    gotoxy(x + 11, y + 5);
    printf("#");
    gotoxy(x + 11, y + 6);
    printf("#");
    gotoxy(x + 11, y + 7);
    printf("#");
    gotoxy(x + 11, y + 8);
    printf("#");
    gotoxy(x + 11, y + 9);
    printf("#");
    gotoxy(x + 11, y + 10);
    printf("#");
    gotoxy(x + 1, y + 11);
    printf("##########");
    gotoxy(x, y + 12);
    printf("#");
    gotoxy(x, y + 13);
    printf("#");
    gotoxy(x, y + 14);
    printf("#");
    gotoxy(x, y + 15);
    printf("#");
    gotoxy(x, y + 16);
    printf("#");
    gotoxy(x, y + 17);
    printf("#");
    gotoxy(x, y + 18);
    printf("#");
    gotoxy(x, y + 19);
    printf("#");
    gotoxy(x, y + 20);
    printf("#");
    gotoxy(x, y + 21);
    printf("#");
    gotoxy(x + 11, y + 12);
    printf(" ");
    gotoxy(x + 11, y + 13);
    printf(" ");
    gotoxy(x + 11, y + 14);
    printf(" ");
    gotoxy(x + 11, y + 15);
    printf(" ");
    gotoxy(x + 11, y + 16);
    printf(" ");
    gotoxy(x + 11, y + 17);
    printf(" ");
    gotoxy(x + 11, y + 18);
    printf(" ");
    gotoxy(x + 11, y + 19);
    printf(" ");
    gotoxy(x + 11, y + 20);
    printf(" ");
    gotoxy(x + 11, y + 21);
    printf(" ");
    gotoxy(x + 1, y + 22);
    printf("##########");
}

Digit3(int x, int  y)
{
    gotoxy(x + 1, y);
    printf("##########");
    gotoxy(x, y + 1);
    printf(" ");
    gotoxy(x, y + 2);
    printf(" ");
    gotoxy(x, y + 3);
    printf(" ");
    gotoxy(x, y + 4);
    printf(" ");
    gotoxy(x, y + 5);
    printf(" ");
    gotoxy(x, y + 6);
    printf(" ");
    gotoxy(x, y + 7);
    printf(" ");
    gotoxy(x, y + 8);
    printf(" ");
    gotoxy(x, y + 9);
    printf(" ");
    gotoxy(x, y + 10);
    printf(" ");
    gotoxy(x + 11, y + 1);
    printf("#");
    gotoxy(x + 11, y + 2);
    printf("#");
    gotoxy(x + 11, y + 3);
    printf("#");
    gotoxy(x + 11, y + 4);
    printf("#");
    gotoxy(x + 11, y + 5);
    printf("#");
    gotoxy(x + 11, y + 6);
    printf("#");
    gotoxy(x + 11, y + 7);
    printf("#");
    gotoxy(x + 11, y + 8);
    printf("#");
    gotoxy(x + 11, y + 9);
    printf("#");
    gotoxy(x + 11, y + 10);
    printf("#");
    gotoxy(x + 1, y + 11);
    printf("##########");
    gotoxy(x, y + 12);
    printf(" ");
    gotoxy(x, y + 13);
    printf(" ");
    gotoxy(x, y + 14);
    printf(" ");
    gotoxy(x, y + 15);
    printf(" ");
    gotoxy(x, y + 16);
    printf(" ");
    gotoxy(x, y + 17);
    printf(" ");
    gotoxy(x, y + 18);
    printf(" ");
    gotoxy(x, y + 19);
    printf(" ");
    gotoxy(x, y + 20);
    printf(" ");
    gotoxy(x, y + 21);
    printf(" ");
    gotoxy(x + 11, y + 12);
    printf("#");
    gotoxy(x + 11, y + 13);
    printf("#");
    gotoxy(x + 11, y + 14);
    printf("#");
    gotoxy(x + 11, y + 15);
    printf("#");
    gotoxy(x + 11, y + 16);
    printf("#");
    gotoxy(x + 11, y + 17);
    printf("#");
    gotoxy(x + 11, y + 18);
    printf("#");
    gotoxy(x + 11, y + 19);
    printf("#");
    gotoxy(x + 11, y + 20);
    printf("#");
    gotoxy(x + 11, y + 21);
    printf("#");
    gotoxy(x + 1, y + 22);
    printf("##########");
}

Digit4(int x, int  y)
{
    gotoxy(x + 1, y);
    printf("          ");
    gotoxy(x, y + 1);
    printf("#");
    gotoxy(x, y + 2);
    printf("#");
    gotoxy(x, y + 3);
    printf("#");
    gotoxy(x, y + 4);
    printf("#");
    gotoxy(x, y + 5);
    printf("#");
    gotoxy(x, y + 6);
    printf("#");
    gotoxy(x, y + 7);
    printf("#");
    gotoxy(x, y + 8);
    printf("#");
    gotoxy(x, y + 9);
    printf("#");
    gotoxy(x, y + 10);
    printf("#");
    gotoxy(x + 11, y + 1);
    printf("#");
    gotoxy(x + 11, y + 2);
    printf("#");
    gotoxy(x + 11, y + 3);
    printf("#");
    gotoxy(x + 11, y + 4);
    printf("#");
    gotoxy(x + 11, y + 5);
    printf("#");
    gotoxy(x + 11, y + 6);
    printf("#");
    gotoxy(x + 11, y + 7);
    printf("#");
    gotoxy(x + 11, y + 8);
    printf("#");
    gotoxy(x + 11, y + 9);
    printf("#");
    gotoxy(x + 11, y + 10);
    printf("#");
    gotoxy(x + 1, y + 11);
    printf("##########");
    gotoxy(x, y + 12);
    printf(" ");
    gotoxy(x, y + 13);
    printf(" ");
    gotoxy(x, y + 14);
    printf(" ");
    gotoxy(x, y + 15);
    printf(" ");
    gotoxy(x, y + 16);
    printf(" ");
    gotoxy(x, y + 17);
    printf(" ");
    gotoxy(x, y + 18);
    printf(" ");
    gotoxy(x, y + 19);
    printf(" ");
    gotoxy(x, y + 20);
    printf(" ");
    gotoxy(x, y + 21);
    printf(" ");
    gotoxy(x + 11, y + 12);
    printf("#");
    gotoxy(x + 11, y + 13);
    printf("#");
    gotoxy(x + 11, y + 14);
    printf("#");
    gotoxy(x + 11, y + 15);
    printf("#");
    gotoxy(x + 11, y + 16);
    printf("#");
    gotoxy(x + 11, y + 17);
    printf("#");
    gotoxy(x + 11, y + 18);
    printf("#");
    gotoxy(x + 11, y + 19);
    printf("#");
    gotoxy(x + 11, y + 20);
    printf("#");
    gotoxy(x + 11, y + 21);
    printf("#");
    gotoxy(x + 1, y + 22);
    printf("          ");
}

Digit5(int x, int  y)
{
    gotoxy(x + 1, y);
    printf("##########");
    gotoxy(x, y + 1);
    printf("#");
    gotoxy(x, y + 2);
    printf("#");
    gotoxy(x, y + 3);
    printf("#");
    gotoxy(x, y + 4);
    printf("#");
    gotoxy(x, y + 5);
    printf("#");
    gotoxy(x, y + 6);
    printf("#");
    gotoxy(x, y + 7);
    printf("#");
    gotoxy(x, y + 8);
    printf("#");
    gotoxy(x, y + 9);
    printf("#");
    gotoxy(x, y + 10);
    printf("#");
    gotoxy(x + 11, y + 1);
    printf(" ");
    gotoxy(x + 11, y + 2);
    printf(" ");
    gotoxy(x + 11, y + 3);
    printf(" ");
    gotoxy(x + 11, y + 4);
    printf(" ");
    gotoxy(x + 11, y + 5);
    printf(" ");
    gotoxy(x + 11, y + 6);
    printf(" ");
    gotoxy(x + 11, y + 7);
    printf(" ");
    gotoxy(x + 11, y + 8);
    printf(" ");
    gotoxy(x + 11, y + 9);
    printf(" ");
    gotoxy(x + 11, y + 10);
    printf(" ");
    gotoxy(x + 1, y + 11);
    printf("##########");
    gotoxy(x, y + 12);
    printf(" ");
    gotoxy(x, y + 13);
    printf(" ");
    gotoxy(x, y + 14);
    printf(" ");
    gotoxy(x, y + 15);
    printf(" ");
    gotoxy(x, y + 16);
    printf(" ");
    gotoxy(x, y + 17);
    printf(" ");
    gotoxy(x, y + 18);
    printf(" ");
    gotoxy(x, y + 19);
    printf(" ");
    gotoxy(x, y + 20);
    printf(" ");
    gotoxy(x, y + 21);
    printf(" ");
    gotoxy(x + 11, y + 12);
    printf("#");
    gotoxy(x + 11, y + 13);
    printf("#");
    gotoxy(x + 11, y + 14);
    printf("#");
    gotoxy(x + 11, y + 15);
    printf("#");
    gotoxy(x + 11, y + 16);
    printf("#");
    gotoxy(x + 11, y + 17);
    printf("#");
    gotoxy(x + 11, y + 18);
    printf("#");
    gotoxy(x + 11, y + 19);
    printf("#");
    gotoxy(x + 11, y + 20);
    printf("#");
    gotoxy(x + 11, y + 21);
    printf("#");
    gotoxy(x + 1, y + 22);
    printf("##########");
}

Digit6(int x, int  y)
{
    gotoxy(x + 1, y);
    printf("##########");
    gotoxy(x, y + 1);
    printf("#");
    gotoxy(x, y + 2);
    printf("#");
    gotoxy(x, y + 3);
    printf("#");
    gotoxy(x, y + 4);
    printf("#");
    gotoxy(x, y + 5);
    printf("#");
    gotoxy(x, y + 6);
    printf("#");
    gotoxy(x, y + 7);
    printf("#");
    gotoxy(x, y + 8);
    printf("#");
    gotoxy(x, y + 9);
    printf("#");
    gotoxy(x, y + 10);
    printf("#");
    gotoxy(x + 11, y + 1);
    printf(" ");
    gotoxy(x + 11, y + 2);
    printf(" ");
    gotoxy(x + 11, y + 3);
    printf(" ");
    gotoxy(x + 11, y + 4);
    printf(" ");
    gotoxy(x + 11, y + 5);
    printf(" ");
    gotoxy(x + 11, y + 6);
    printf(" ");
    gotoxy(x + 11, y + 7);
    printf(" ");
    gotoxy(x + 11, y + 8);
    printf(" ");
    gotoxy(x + 11, y + 9);
    printf(" ");
    gotoxy(x + 11, y + 10);
    printf(" ");
    gotoxy(x + 1, y + 11);
    printf("##########");
    gotoxy(x, y + 12);
    printf("#");
    gotoxy(x, y + 13);
    printf("#");
    gotoxy(x, y + 14);
    printf("#");
    gotoxy(x, y + 15);
    printf("#");
    gotoxy(x, y + 16);
    printf("#");
    gotoxy(x, y + 17);
    printf("#");
    gotoxy(x, y + 18);
    printf("#");
    gotoxy(x, y + 19);
    printf("#");
    gotoxy(x, y + 20);
    printf("#");
    gotoxy(x, y + 21);
    printf("#");
    gotoxy(x + 11, y + 12);
    printf("#");
    gotoxy(x + 11, y + 13);
    printf("#");
    gotoxy(x + 11, y + 14);
    printf("#");
    gotoxy(x + 11, y + 15);
    printf("#");
    gotoxy(x + 11, y + 16);
    printf("#");
    gotoxy(x + 11, y + 17);
    printf("#");
    gotoxy(x + 11, y + 18);
    printf("#");
    gotoxy(x + 11, y + 19);
    printf("#");
    gotoxy(x + 11, y + 20);
    printf("#");
    gotoxy(x + 11, y + 21);
    printf("#");
    gotoxy(x + 1, y + 22);
    printf("##########");
}

Digit7(int x, int  y)
{
    gotoxy(x + 1, y);
    printf("##########");
    gotoxy(x, y + 1);
    printf("#");
    gotoxy(x, y + 2);
    printf("#");
    gotoxy(x, y + 3);
    printf("#");
    gotoxy(x, y + 4);
    printf("#");
    gotoxy(x, y + 5);
    printf("#");
    gotoxy(x, y + 6);
    printf("#");
    gotoxy(x, y + 7);
    printf("#");
    gotoxy(x, y + 8);
    printf("#");
    gotoxy(x, y + 9);
    printf("#");
    gotoxy(x, y + 10);
    printf("#");
    gotoxy(x + 11, y + 1);
    printf("#");
    gotoxy(x + 11, y + 2);
    printf("#");
    gotoxy(x + 11, y + 3);
    printf("#");
    gotoxy(x + 11, y + 4);
    printf("#");
    gotoxy(x + 11, y + 5);
    printf("#");
    gotoxy(x + 11, y + 6);
    printf("#");
    gotoxy(x + 11, y + 7);
    printf("#");
    gotoxy(x + 11, y + 8);
    printf("#");
    gotoxy(x + 11, y + 9);
    printf("#");
    gotoxy(x + 11, y + 10);
    printf("#");
    gotoxy(x + 1, y + 11);
    printf("          ");
    gotoxy(x, y + 12);
    printf(" ");
    gotoxy(x, y + 13);
    printf(" ");
    gotoxy(x, y + 14);
    printf(" ");
    gotoxy(x, y + 15);
    printf(" ");
    gotoxy(x, y + 16);
    printf(" ");
    gotoxy(x, y + 17);
    printf(" ");
    gotoxy(x, y + 18);
    printf(" ");
    gotoxy(x, y + 19);
    printf(" ");
    gotoxy(x, y + 20);
    printf(" ");
    gotoxy(x, y + 21);
    printf(" ");
    gotoxy(x + 11, y + 12);
    printf("#");
    gotoxy(x + 11, y + 13);
    printf("#");
    gotoxy(x + 11, y + 14);
    printf("#");
    gotoxy(x + 11, y + 15);
    printf("#");
    gotoxy(x + 11, y + 16);
    printf("#");
    gotoxy(x + 11, y + 17);
    printf("#");
    gotoxy(x + 11, y + 18);
    printf("#");
    gotoxy(x + 11, y + 19);
    printf("#");
    gotoxy(x + 11, y + 20);
    printf("#");
    gotoxy(x + 11, y + 21);
    printf("#");
    gotoxy(x + 1, y + 22);
    printf("          ");
}

Digit8(int x, int  y)
{
    gotoxy(x + 1, y);
    printf("##########");
    gotoxy(x, y + 1);
    printf("#");
    gotoxy(x, y + 2);
    printf("#");
    gotoxy(x, y + 3);
    printf("#");
    gotoxy(x, y + 4);
    printf("#");
    gotoxy(x, y + 5);
    printf("#");
    gotoxy(x, y + 6);
    printf("#");
    gotoxy(x, y + 7);
    printf("#");
    gotoxy(x, y + 8);
    printf("#");
    gotoxy(x, y + 9);
    printf("#");
    gotoxy(x, y + 10);
    printf("#");
    gotoxy(x + 11, y + 1);
    printf("#");
    gotoxy(x + 11, y + 2);
    printf("#");
    gotoxy(x + 11, y + 3);
    printf("#");
    gotoxy(x + 11, y + 4);
    printf("#");
    gotoxy(x + 11, y + 5);
    printf("#");
    gotoxy(x + 11, y + 6);
    printf("#");
    gotoxy(x + 11, y + 7);
    printf("#");
    gotoxy(x + 11, y + 8);
    printf("#");
    gotoxy(x + 11, y + 9);
    printf("#");
    gotoxy(x + 11, y + 10);
    printf("#");
    gotoxy(x + 1, y + 11);
    printf("##########");
    gotoxy(x, y + 12);
    printf("#");
    gotoxy(x, y + 13);
    printf("#");
    gotoxy(x, y + 14);
    printf("#");
    gotoxy(x, y + 15);
    printf("#");
    gotoxy(x, y + 16);
    printf("#");
    gotoxy(x, y + 17);
    printf("#");
    gotoxy(x, y + 18);
    printf("#");
    gotoxy(x, y + 19);
    printf("#");
    gotoxy(x, y + 20);
    printf("#");
    gotoxy(x, y + 21);
    printf("#");
    gotoxy(x + 11, y + 12);
    printf("#");
    gotoxy(x + 11, y + 13);
    printf("#");
    gotoxy(x + 11, y + 14);
    printf("#");
    gotoxy(x + 11, y + 15);
    printf("#");
    gotoxy(x + 11, y + 16);
    printf("#");
    gotoxy(x + 11, y + 17);
    printf("#");
    gotoxy(x + 11, y + 18);
    printf("#");
    gotoxy(x + 11, y + 19);
    printf("#");
    gotoxy(x + 11, y + 20);
    printf("#");
    gotoxy(x + 11, y + 21);
    printf("#");
    gotoxy(x + 1, y + 22);
    printf("##########");
}

Digit9(int x, int  y)
{
    gotoxy(x + 1, y);
    printf("##########");
    gotoxy(x, y + 1);
    printf("#");
    gotoxy(x, y + 2);
    printf("#");
    gotoxy(x, y + 3);
    printf("#");
    gotoxy(x, y + 4);
    printf("#");
    gotoxy(x, y + 5);
    printf("#");
    gotoxy(x, y + 6);
    printf("#");
    gotoxy(x, y + 7);
    printf("#");
    gotoxy(x, y + 8);
    printf("#");
    gotoxy(x, y + 9);
    printf("#");
    gotoxy(x, y + 10);
    printf("#");
    gotoxy(x + 11, y + 1);
    printf("#");
    gotoxy(x + 11, y + 2);
    printf("#");
    gotoxy(x + 11, y + 3);
    printf("#");
    gotoxy(x + 11, y + 4);
    printf("#");
    gotoxy(x + 11, y + 5);
    printf("#");
    gotoxy(x + 11, y + 6);
    printf("#");
    gotoxy(x + 11, y + 7);
    printf("#");
    gotoxy(x + 11, y + 8);
    printf("#");
    gotoxy(x + 11, y + 9);
    printf("#");
    gotoxy(x + 11, y + 10);
    printf("#");
    gotoxy(x + 1, y + 11);
    printf("##########");
    gotoxy(x, y + 12);
    printf(" ");
    gotoxy(x, y + 13);
    printf(" ");
    gotoxy(x, y + 14);
    printf(" ");
    gotoxy(x, y + 15);
    printf(" ");
    gotoxy(x, y + 16);
    printf(" ");
    gotoxy(x, y + 17);
    printf(" ");
    gotoxy(x, y + 18);
    printf(" ");
    gotoxy(x, y + 19);
    printf(" ");
    gotoxy(x, y + 20);
    printf(" ");
    gotoxy(x, y + 21);
    printf(" ");
    gotoxy(x + 11, y + 12);
    printf("#");
    gotoxy(x + 11, y + 13);
    printf("#");
    gotoxy(x + 11, y + 14);
    printf("#");
    gotoxy(x + 11, y + 15);
    printf("#");
    gotoxy(x + 11, y + 16);
    printf("#");
    gotoxy(x + 11, y + 17);
    printf("#");
    gotoxy(x + 11, y + 18);
    printf("#");
    gotoxy(x + 11, y + 19);
    printf("#");
    gotoxy(x + 11, y + 20);
    printf("#");
    gotoxy(x + 11, y + 21);
    printf("#");
    gotoxy(x + 1, y + 22);
    printf("##########");
}
